cronjobs on celery to select verse of the day
gita/bhagavad-gita-api pull request #56
Opened 2021-08-30 19:30 UTC by soni-muskan1234

1. I created a new table in database namely "verse of the day" which saves the verse number .
2. Created an endpoint to select a random verse and save it in table.
3. Used celery over redis which calls the endpoint every midnight thereby setting the verse of the day.
4. If any how that request is sent again then new request will be overruled after checking if entry already exists in table for that day.

2021-09-07 10:15 UTC, Gupta-Anubhav12 requested changes
Please update dependencies in poetry for celery and dependent packages 
thanks

2021-09-09 18:56 UTC, soni-muskan1234 commented
Updated the dependencies , please check
thanks,

2021-09-12 11:09 UTC, samanyougarg commented
It seems to be working well. Great job!
Couple of warnings though:
<img width="725" alt="Screenshot 2021-09-12 at 4 39 17 PM" src="https://user-images.githubusercontent.com/32533774/132985228-65181ea2-be35-43da-b1db-71e9f8b7a1d4.png">

2021-09-12 11:10 UTC, samanyougarg commented
Also, you probably forgot to push the commit for updated dependencies.

2021-09-17 15:26 UTC, samanyougarg commented on bhagavad_gita_api/config.py
> +    # celery cronjobs
Can we read these from the env file please instead of hardcoding them?

2021-09-17 15:28 UTC, samanyougarg commented on bhagavad_gita_api/cronjobs/celery.py
> +        "X-API-KEY": "Shri Hari",
X-API-KEY value shouldn't be hardcoded. Please read from the settings.

2021-09-19 09:26 UTC, Gupta-Anubhav12 commented
> It seems to be working well. Great job!
> Couple of warnings though:
> <img alt="Screenshot 2021-09-12 at 4 39 17 PM" width="725" src="https://user-images.githubusercontent.com/32533774/132985228-65181ea2-be35-43da-b1db-71e9f8b7a1d4.png">

Resolved ,

2021-09-19 09:27 UTC, Gupta-Anubhav12 approved these changes

2021-09-19 10:51 UTC, merged

2021-09-19 10:52 UTC, samanyougarg commented
Great job guys @Gupta-Anubhav12 @soni-muskan1234!!

2021-09-19 13:21 UTC, soni-muskan1234 commented
Thanks!
Looking forward to learn more

2021-10-20 13:29 UTC, Gupta-Anubhav12 commented
@all-contributors please add @soni-muskan1234 for code